### ISSUE TITLE
Evaluation test data

### ISSUE THREAD

**Issue by wedu-nvidia** [sarahmart/HARDMath#1]
Hi Jingxuan,
     I am currently working on evaluating your benchmark dataset using our models. While reviewing the description in the repository, I noticed that it states:

"This repository hosts the [full dataset](https://github.com/sarahmart/HARDMath/blob/main/data/HARDMath.json) and the [evaluation dataset](https://github.com/sarahmart/HARDMath/blob/main/evaluation/data/eval_HARDMath.json)."

However, the link to the evaluation dataset (https://github.com/sarahmart/HARDMath/blob/main/evaluation/data/eval_HARDMath.json) appears to be broken. Additionally, when I checked the dataset via this link, it contained 1060 entries, which seems to be inconsistent with the description in the paper.

Could you kindly provide the training and test data referenced in the paper? I would greatly appreciate it. Thank you!

**Comment by ewang26** [comment]
Hello, apologies for the delayed response! We didn't see this request earlier but appreciate your interest.

Our evaluation data can be accessed [here](https://github.com/sarahmart/HARDMath/tree/main/evaluation/data) — it is the same data that’s already listed on the GitHub under ‘evaluation’. Also, the data referenced in the paper has 1060 entries and is detailed in section 3 (labeled “Datasets”) of the paper. There are 1,466 problems in total. The other number in the introduction corresponded to a prior version of the dataset; we have since updated that point in the manuscript. Thank you for bringing that to our attention.

Please let us know if you have any further questions!

**Comment by wedu-nvidia** [comment]
Thanks so much for your reply and it is super useful

**Comment by ewang26** [comment]
You're welcome! Thank you for your interest, and glad we could help!

**Comment by ewang26** [comment]
You're welcome! Thank you for your interest, and glad we could help!
